const array<array<string>> AUDIO_AMB_NAMES = {
	{
		"amb_birds",
		"amb_city",
		"amb_computers",
		"amb_crickets",
		"amb_hollow",
		"amb_machinery",
		"amb_rain",
		"amb_wind"
	}
};

const array<array<string>> AUDIO_MUSIC_NAMES = {
	{
		"9-bit Expedition",
		"A Safe Place to Sleep",
		"A Square the Rectangle is Not",
		"Baryogenesis",
		"Cider Time",
		"Dream Salvage",
		"Electric Relic",
		"Elvish Piper Academy",
		"Fifty FPS Forest",
		"Frozen Hot Sauce",
		"Introduction",
		"It's Not Supposed To Be Snowing",
		"Light Pollution",
		"Minus",
		"Pillars of Pepper",
		"Sepia Tone Laboratory",
		"Sun Bleach",
		"Swimming Through Waves",
		"Swimming While It Rains",
		"Teacups",
		"The Magnetic Tree",
		"Undiscovery",
		"Upside Down Stalagmite",
		"Your Favorite Color"
	}
};

const array<array<string>> AUDIO_SFX_NAMES = {
	{
		"sfx_animal_land"
	},
	{
		"sfx_barrel_attack",
		"sfx_barrel_land"
	},
	{	
		"sfx_bear_attack",
		"sfx_bear_footstep",
		"sfx_bear_land",
		"sfx_bear_yawn"
	},
	{
		"sfx_bgargoyle_attack",
		"sfx_bgargoyle_footstep",
		"sfx_bgargoyle_land"
	},
	{
		"sfx_book_attack",
		"sfx_book_flap",
		"sfx_book_land"
	},
	{
		"sfx_chest_land"
	},
	{
		"sfx_damage",
		"sfx_damage_spikes"
	},
	{
		"sfx_dg_attack_heavy_1",
		"sfx_dg_attack_heavy_2",
		"sfx_dg_attack_light_1",
		"sfx_dg_attack_light_2",
		"sfx_dg_attack_light_3",
		"sfx_dg_dash_air",
		"sfx_dg_dash_ground",
		"sfx_dg_fast_fall",
		"sfx_dg_jump_air_1",
		"sfx_dg_jump_air_2",
		"sfx_dg_jump_air_3",
		"sfx_dg_jump_ground_1",
		"sfx_dg_jump_ground_2",
		"sfx_dg_jump_ground_3",
		"sfx_dg_jump_wall_1",
		"sfx_dg_jump_wall_2",
		"sfx_dg_jump_wall_3",
		"sfx_dg_special_activate",
		"sfx_dg_special_final",
		"sfx_dg_special_hit",
		"sfx_dg_special_ready",
		"sfx_dg_sweep_1",
		"sfx_dg_sweep_2",
		"sfx_dg_sweep_3"
	},
	{
		"sfx_dk_attack_heavy_1",
		"sfx_dk_attack_heavy_2",
		"sfx_dk_attack_light_1",
		"sfx_dk_attack_light_2",
		"sfx_dk_attack_light_3",
		"sfx_dk_dash_air",
		"sfx_dk_dash_ground",
		"sfx_dk_fast_fall",
		"sfx_dk_jump_air_1",
		"sfx_dk_jump_air_2",
		"sfx_dk_jump_air_3",
		"sfx_dk_jump_ground_1",
		"sfx_dk_jump_ground_2",
		"sfx_dk_jump_ground_3",
		"sfx_dk_jump_wall_1",
		"sfx_dk_jump_wall_2",
		"sfx_dk_jump_wall_3",
		"sfx_dk_special_activate",
		"sfx_dk_special_final",
		"sfx_dk_special_hit",
		"sfx_dk_special_ready",
		"sfx_dk_sweep_1",
		"sfx_dk_sweep_2",
		"sfx_dk_sweep_3"
	},
	{
		"sfx_dm_attack_heavy_1",
		"sfx_dm_attack_heavy_2",
		"sfx_dm_attack_light_1",
		"sfx_dm_attack_light_2",
		"sfx_dm_attack_light_3",
		"sfx_dm_dash_air",
		"sfx_dm_dash_ground",
		"sfx_dm_fast_fall",
		"sfx_dm_jump_air_1",
		"sfx_dm_jump_air_2",
		"sfx_dm_jump_air_3",
		"sfx_dm_jump_ground_1",
		"sfx_dm_jump_ground_2",
		"sfx_dm_jump_ground_3",
		"sfx_dm_jump_wall_1",
		"sfx_dm_jump_wall_2",
		"sfx_dm_jump_wall_3",
		"sfx_dm_special_activate",
		"sfx_dm_special_final",
		"sfx_dm_special_hit",
		"sfx_dm_special_ready",
		"sfx_dm_sweep_1",
		"sfx_dm_sweep_2",
		"sfx_dm_sweep_3"
	},
	{
		"sfx_do_attack_heavy_1",
		"sfx_do_attack_heavy_2",
		"sfx_do_attack_light_1",
		"sfx_do_attack_light_2",
		"sfx_do_attack_light_3",
		"sfx_do_dash_air",
		"sfx_do_dash_ground",
		"sfx_do_fast_fall",
		"sfx_do_jump_air_1",
		"sfx_do_jump_air_2",
		"sfx_do_jump_air_3",
		"sfx_do_jump_ground_1",
		"sfx_do_jump_ground_2",
		"sfx_do_jump_ground_3",
		"sfx_do_jump_wall_1",
		"sfx_do_jump_wall_2",
		"sfx_do_jump_wall_3",
		"sfx_do_special_activate",
		"sfx_do_special_final",
		"sfx_do_special_hit",
		"sfx_do_special_ready",
		"sfx_do_sweep_1",
		"sfx_do_sweep_2",
		"sfx_do_sweep_3"
	},
	{
		"sfx_door_city",
		"sfx_door_lab",
		"sfx_door_land",
		"sfx_door_stone_open",
		"sfx_door_stone_unlock",
		"sfx_door_unlock",
		"sfx_door_unlock",
		"sfx_door_wood_open",
		"sfx_door_wood_unlock"
	},
	{
		"sfx_dust_heavy",
		"sfx_dust_light_1",
		"sfx_dust_light_2",
		"sfx_dust_light_3",
		"sfx_dust_med"
	},
	{
		"sfx_dw_attack_heavy_1",
		"sfx_dw_attack_heavy_2",
		"sfx_dw_attack_light_1",
		"sfx_dw_attack_light_2",
		"sfx_dw_attack_light_3",
		"sfx_dw_dash_air",
		"sfx_dw_dash_ground",
		"sfx_dw_fast_fall",
		"sfx_dw_jump_air_1",
		"sfx_dw_jump_air_2",
		"sfx_dw_jump_air_3",
		"sfx_dw_jump_ground_1",
		"sfx_dw_jump_ground_2",
		"sfx_dw_jump_ground_3",
		"sfx_dw_jump_wall_1",
		"sfx_dw_jump_wall_2",
		"sfx_dw_jump_wall_3",
		"sfx_dw_special_activate",
		"sfx_dw_special_final",
		"sfx_dw_special_hit",
		"sfx_dw_special_ready",
		"sfx_dw_sweep_1",
		"sfx_dw_sweep_2",
		"sfx_dw_sweep_3"
	},
	{
		"sfx_footstep_carpet_1",
		"sfx_footstep_carpet_2",
		"sfx_footstep_carpet_3",
		"sfx_footstep_dirt_1",
		"sfx_footstep_dirt_2",
		"sfx_footstep_dirt_3",
		"sfx_footstep_grass_1",
		"sfx_footstep_grass_2",
		"sfx_footstep_grass_3",
		"sfx_footstep_metal_1",
		"sfx_footstep_metal_2",
		"sfx_footstep_metal_3",
		"sfx_footstep_poly_1",
		"sfx_footstep_poly_2",
		"sfx_footstep_poly_3",
		"sfx_footstep_stone_1",
		"sfx_footstep_stone_2",
		"sfx_footstep_stone_3",
		"sfx_footstep_water_1",
		"sfx_footstep_water_2",
		"sfx_footstep_water_3",
		"sfx_footstep_wood_1",
		"sfx_footstep_wood_2",
		"sfx_footstep_wood_3"
	},
	{
		"sfx_gargoyle_fly"
	},
	{
		"sfx_hawk_attack",
		"sfx_hawk_flap",
		"sfx_hawk_flap_leaf"
	},
	{
		"sfx_hill_beep",
		"sfx_hill_get",
		"sfx_hill_lost",
		"sfx_hill_score"
	},
	{
		"sfx_hud_cancel_1",
		"sfx_hud_cancel_2",
		"sfx_hud_cancel_3",
		"sfx_hud_cancel_4",
		"sfx_hud_highlight_1",
		"sfx_hud_highlight_2",
		"sfx_hud_highlight_3",
		"sfx_hud_highlight_4",
		"sfx_hud_level_start",
		"sfx_hud_score_hit",
		"sfx_hud_select_1",
		"sfx_hud_select_2",
		"sfx_hud_select_3",
		"sfx_hud_select_4"
	},
	{
		"sfx_impact_heavy_1",
		"sfx_impact_heavy_2",
		"sfx_impact_heavy_3",
		"sfx_impact_light_1",
		"sfx_impact_light_2",
		"sfx_impact_light_3",
		"sfx_impact_parry"
	},
	{
		"sfx_knight_attack",
		"sfx_knight_block",
		"sfx_knight_footstep",
		"sfx_knight_land"
	},
	{
		"sfx_land_carpet",
		"sfx_land_dirt",
		"sfx_land_generic_heavy",
		"sfx_land_grass",
		"sfx_land_metal",
		"sfx_land_poly",
		"sfx_land_stone",
		"sfx_land_water",
		"sfx_land_wood"
	},
	{
		"sfx_leaf_heavy",
		"sfx_leaf_light_1",
		"sfx_leaf_light_2",
		"sfx_leaf_light_3",
		"sfx_leaf_med"
	},
	{
		"sfx_ls_attack_heavy_1",
		"sfx_ls_attack_heavy_2",
		"sfx_ls_attack_light_1",
		"sfx_ls_attack_light_2",
		"sfx_ls_attack_light_3",
		"sfx_ls_dash_air",
		"sfx_ls_dash_ground",
		"sfx_ls_fast_fall",
		"sfx_ls_jump_air_1",
		"sfx_ls_jump_air_2",
		"sfx_ls_jump_air_3",
		"sfx_ls_jump_ground_1",
		"sfx_ls_jump_ground_2",
		"sfx_ls_jump_ground_3",
		"sfx_ls_jump_wall_1",
		"sfx_ls_jump_wall_2",
		"sfx_ls_jump_wall_3",
		"sfx_ls_special_activate",
		"sfx_ls_special_final",
		"sfx_ls_special_hit",
		"sfx_ls_special_ready",
		"sfx_ls_sweep_1",
		"sfx_ls_sweep_2",
		"sfx_ls_sweep_3"
	},
	{
		"sfx_poly_heavy",
		"sfx_poly_light_1",
		"sfx_poly_light_2",
		"sfx_poly_light_3",
		"sfx_poly_med"
	},
	{
		"sfx_porcupine_attack"
	},
	{
		"sfx_respawn"
	},
	{
		"sfx_sb_attack_heavy_1",
		"sfx_sb_attack_heavy_2",
		"sfx_sb_attack_light_1",
		"sfx_sb_attack_light_2",
		"sfx_sb_attack_light_3",
		"sfx_sb_dash_air",
		"sfx_sb_dash_ground",
		"sfx_sb_fast_fall",
		"sfx_sb_jump_air_1",
		"sfx_sb_jump_air_2",
		"sfx_sb_jump_air_3",
		"sfx_sb_jump_ground_1",
		"sfx_sb_jump_ground_2",
		"sfx_sb_jump_ground_3",
		"sfx_sb_jump_wall_1",
		"sfx_sb_jump_wall_2",
		"sfx_sb_jump_wall_3",
		"sfx_sb_special_activate",
		"sfx_sb_special_final",
		"sfx_sb_special_hit",
		"sfx_sb_special_ready",
		"sfx_sb_sweep_1",
		"sfx_sb_sweep_2",
		"sfx_sb_sweep_3"
	},
	{
		"sfx_scroll_land",
		"sfx_scroll_ruffle"
	},
	{
		"sfx_slide_carpet_loop",
		"sfx_slide_dirt_loop",
		"sfx_slide_grass_loop",
		"sfx_slide_metal_loop",
		"sfx_slide_poly_loop",
		"sfx_slide_stone_loop",
		"sfx_slide_water_loop",
		"sfx_slide_wood_loop"
	},
	{
		"sfx_slime_heavy",
		"sfx_slime_light_1",
		"sfx_slime_light_2",
		"sfx_slime_light_3",
		"sfx_slime_light_4",
		"sfx_slime_light_5",
		"sfx_slime_light_6",
		"sfx_slime_light_overlay_1",
		"sfx_slime_light_overlay_2",
		"sfx_slime_light_overlay_3",
		"sfx_slime_light_overlay_4",
		"sfx_slime_light_overlay_5",
		"sfx_slime_light_overlay_6",
		"sfx_slime_med"
	},
	{
		"sfx_slimebeast_attack",
		"sfx_slimebeast_footstep",
		"sfx_slimebeast_land"
	},
	{
		"sfx_sparks_1",
		"sfx_sparks_2",
		"sfx_sparks_3",
		"sfx_sparks_4",
		"sfx_sparks_5",
		"sfx_sparks_6",
		"sfx_sparks_7",
		"sfx_sparks_8",
		"sfx_sparks_9",
		"sfx_sparks_10",
		"sfx_sparks_11",
		"sfx_sparks_12"
	},
	{
		"sfx_springball_attack_end",
		"sfx_springball_attack_start",
		"sfx_springball_bounce",
		"sfx_springball_land_heavy",
		"sfx_springball_land_light"
	},
	{
		"sfx_stone_land",
		"sfx_stoneboss_jump",
		"sfx_stoneboss_land",
		"sfx_stonebro_attack"
	},
	{
		"sfx_tchest_land"
	},
	{
		"sfx_tk_attack_heavy_1",
		"sfx_tk_attack_heavy_2",
		"sfx_tk_attack_light_1",
		"sfx_tk_attack_light_2",
		"sfx_tk_attack_light_3",
		"sfx_tk_dash_air",
		"sfx_tk_dash_ground",
		"sfx_tk_fast_fall",
		"sfx_tk_jump_air_1",
		"sfx_tk_jump_air_2",
		"sfx_tk_jump_air_3",
		"sfx_tk_jump_ground_1",
		"sfx_tk_jump_ground_2",
		"sfx_tk_jump_ground_3",
		"sfx_tk_jump_wall_1",
		"sfx_tk_jump_wall_2",
		"sfx_tk_jump_wall_3",
		"sfx_tk_special_activate",
		"sfx_tk_special_final",
		"sfx_tk_special_hit",
		"sfx_tk_special_ready",
		"sfx_tk_sweep_1",
		"sfx_tk_sweep_2",
		"sfx_tk_sweep_3"
	},
	{
		"sfx_trash_heavy",
		"sfx_trash_light_1",
		"sfx_trash_light_2",
		"sfx_trash_light_3",
		"sfx_trash_light_4",
		"sfx_trash_light_5",
		"sfx_trash_light_6",
		"sfx_trash_light_7",
		"sfx_trash_light_8",
		"sfx_trash_light_9",
		"sfx_trash_light_10",
		"sfx_trash_med"
	},
	{
		"sfx_trashbag_explode",
		"sfx_trashcan_attack",
		"sfx_trashcan_land"
	},
	{
		"sfx_trashbeast_attack",
		"sfx_trashbeast_footstep",
		"sfx_trashbeast_land"
	},
	{
		"sfx_trashtire_bounce",
		"sfx_trashtire_land"
	},
	{
		"sfx_treasure_fly",
		"sfx_treasure_land"
	},
	{
		"sfx_wind_loop",
		"sfx_wolf_attack"
	},
	{
		"sfx_wolf_footstep"
	}
};